#!/bin/sh

alias ls='ls --color'
alias ll='ls -l'
alias all='ls -al'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
chpwd() { ll }                          # always list upon pwd changed
mcd () { mkdir -p "$1" && cd "$1"; }    # make new dir and cd into it
rmf () {
	DO_NOT_DELETE=("$HOME")
	file=$(realpath $1)
	if [[ " ${DO_NOT_DELETE[@]} " =~ " ${file} " ]]; then
		echo "Remove $file is dangerous!!!"
	else
		rm -rf $1
	fi
}

# git aliases
alias gs='git status'
alias gc='git checkout'
alias gp='git pull'
alias gd='git diff'
