#!/bin/sh

export CLICOLOR=1

alias vi='nvim'
alias vim='nvim'
alias e="emacsclient -a ''"

alias ll='ls -l'
alias all='ls -al'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
chpwd() { ll }                          # always list upon pwd changed
mcd () { mkdir -p "$1" && cd "$1"; }    # make new dir and cd into it

# git aliases
alias g='git'
alias ga='git add --patch'
alias gs='g status'
alias gc='g checkout'
alias gp='g pull'
alias gd='g diff'
alias gl='g log'
alias gg='g graph'

alias ta='tmux attach'
alias tl='tmux ls'
alias tn='tmux new -s'

alias tf='terraform'

hash -d platform=~/workspaces/indebted/platform
hash -d infra=~/workspaces/indebted/infra
