#!/bin/sh

export CLICOLOR=1

# vim
alias vi='nvim'
alias vim='nvim'
alias v='nvim'

# emacs
function start_emacs() {
  if [ "$1" != "" ]; then
    emacsclient -a '' $1
  else
    emacsclient -a '' -nw
  fi
}
alias e='start_emacs'

# background jobs
function fzf_fg() {
  fg %$(jobs | fzf |awk -F'[][]' '{print ($2)}')
}
alias ff='fzf_fg'

alias ll='ls -l'
alias all='ls -al'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
chpwd() { ll }                          # always list upon pwd changed
mcd () { mkdir -p "$1" && cd "$1"; }    # make new dir and cd into it

# git aliases
alias g='git'
alias ga='git add --patch'
alias gs='g status'
alias gc='g checkout'
alias gp='g pull'
alias gd='g diff'
alias gl='g log'
alias gg='g graph'

alias dev='kitty +kitten ssh -p22 namnguyen@192.168.64.45'
