#!/bin/sh

export CLICOLOR=1

alias ll='ls -l'
alias all='ls -al'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
chpwd() { ll }                          # always list upon pwd changed
mcd () { mkdir -p "$1" && cd "$1"; }    # make new dir and cd into it

# git aliases
alias gs='git status'
alias gc='git checkout'
alias gp='git pull'
alias gd='git diff'
alias gb='git branch'
alias gl='git log'

alias ta='tmux attach'
alias tat='tmux attach -t'
alias tl='tmux ls'
alias tn='tmux new -s'

alias dp='docker ps'
alias dpa='docker ps -a'
alias dr='docker restart'
alias dl='docker logs'
alias dcd='docker-compose down'
alias dcu='docker-compose up -d --build'

alias tf='terraform'
